services:
  auth_service:
    build: ./auth_service
    ports:
      - "5001:5001"
    depends_on:
      - auth_db
    networks:
      - app_network
    restart: always

  auth_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
    restart: always
    volumes:
    - auth_db_data:/var/lib/postgresql/data 

networks:
  app_network:
    driver: bridge

volumes:
  auth_db_data:
  task_db_data:
